name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-token-text-view-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install swiftlint
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/realm/SwiftLint
          version: "*"
      - name: Run swiftlint
        run: swiftlint
      - uses: open-turo/action-pre-commit@v1

  test:
    name: Test
    runs-on: macos-latest
    # needs: [lint]  # Uncomment if tests are slow
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: swift build -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios16.2-simulator"
      - name: Reset Simulator privacy settings
        run: xcrun simctl privacy
      - name: Run tests
        run: xcodebuild test -scheme TokenTextView -sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)" -target x86_64-apple-ios16.2-simulator -destination "OS=16.2,name=iPhone 13 Pro"
