name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v \
          -Xswiftc "-sdk" \
          -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
          -Xswiftc "-target" \
          -Xswiftc "x86_64-apple-ios13.0-simulator"
      - name: Run tests
        run: swift test -v
